version: "3"
services:
  bursdag:
    image: technocake/bursdag.club:latest
    build:
      context: .
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
