# Generated by Django 2.2.4 on 2019-09-03 12:06

from django.db import migrations, models
import invite.models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('Opprettet', 'Opprettet'), ('Invitert', 'Invitert'), ('Kommer', 'Kommer'), ('Kommer ikke', 'Kommer ikke')], default='Opprettet', help_text='Status på invitasjonen', max_length=32),
        ),
        migrations.AlterField(
            model_name='invite',
            name='name',
            field=models.CharField(help_text='Navnet til den som er invitert', max_length=255),
        ),
        migrations.AlterField(
            model_name='invite',
            name='pokemon',
            field=models.CharField(choices=[('Jolteon', 'Jolteon'), ('Flareon', 'Flareon'), ('Vaporeon', 'Vaporeon')], default=invite.models.pick_random_pokemon, help_text='Velg en av de tre pokemonene', max_length=32),
        ),
    ]
